baseURL = "https://jenlky.com/"
languageCode = "en-us"
title = "Jenssen Lee"
copyright = "This is a customized copyright."
theme = "diary"
disqusShortname = "jenlky"
googleAnalytics = "UA-139118044-2"

[params]
  disableToC= true
  subtitle = "Themed by Diary."

[taxonomies]
  tag = "tags"
  category = "categories"

[[menu.main]]
  url = "/portfolio"
  name = "Portfolio"
  weight = 1

[[menu.main]]
  url = "/writings"
  name = "Writings"
  weight = 2

[[menu.main]]
  url = "/tags"
  name = "Tags"
  weight = 3
