baseURL = "https://jenlky.com/"
languageCode = "en-us"
title = "Jenssen Lee"
copyright = "2018 - 2021 Jenssen Lee"
theme = "diary"
paginate = 1000
googleAnalytics = "UA-139118044-1"

[params]
  disableToC= true
  subtitle = "Reorienting yourself on the superhighway"
  enableGitalk = false
  enableReadingTime = true
  disqusShortname = "jenlky"

[taxonomies]
  tag = "tags"
  category = "categories"

[[menu.main]]
  url = "/portfolio"
  name = "Portfolio"
  weight = 1

[[menu.main]]
  url = "/writings"
  name = "Writings"
  weight = 2

[[menu.main]]
  url = "/tags"
  name = "Tags"
  weight = 3
